#!/bin/sh

HISTSIZE=1000000
SAVEHIST=1000000

export PATH=$HOME/bin:/usr/local/bin:~/.composer/vendor/bin:$PATH
export CLICOLOR=1

# AWS Stuff
export RP_INFRA_LIVE_ROOT=$HOME/Code/aws/infrastructure-live
export RP_INFRA_MODULES_ROOT=$HOME/Code/aws/infrastructure-modules
export RP_INFRA_TOOLS_ROOT=$HOME/Code/aws/infrastructure-tools
export RP_ROLE_NAME=allow-dev-access-from-other-accounts
source $RP_INFRA_TOOLS_ROOT/init.sh

export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"

