#!/bin/sh
alias vim="nvim"
alias v="nvim"
alias gaa="git add ."
alias gc="git commit -m"
alias gp="git push"
alias dc="docker compose"
alias tuns01="ssh mtroesken@docker-s01.nexinto1.ratepay.com -L 8500:localhost:8500"
alias tunp01="ssh mtroesken@docker-downstream-p01.nexinto1.ratepay.com -L 8500:localhost:8500"
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias wst="watson start ratepay +CINF"
alias wft="watson stop"
alias ssh='TERM=xterm-256color ssh'
alias ll="ls -l"

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

